Js latest featured projects
front-end-by-rimantas/35-grupe-portfolio-personal pull request #104
Opened 2022-04-22 13:34 UTC by krikri89

2022-04-22 14:23 UTC, Dovile-dote requested changes
nesudejai for cikle sriftu pavadinimu

2022-04-22 14:23 UTC, Dovile-dote commented on index.html
> -          <h3 class="section-smaller">3D Helmet Design</h3>
kur dingo .section-smaller ir .section-description klases for cikle?

2022-04-23 15:23 UTC, Dovile-dote approved these changes
atrodo viskas gerai, liuks

2022-04-23 17:33 UTC, krikri89 commented
kazkas nesueina, kai kur titles igavo background-spalva. dar neapprove, please

2022-04-23 18:02 UTC, Dovile-dote reviewed
sriftai gali nesueiti, nes kai kurios sriftu klases turejo tokius pacius pavadinimus skirtinguose css failuose, dar pasitikrink ant kurios develop versijos dirbi, naujausioj jau lyg ir nebesipesa klases, gali buti kad kazka reiks paciai sriftu stiliuje modifikuot :)

2022-04-23 18:03 UTC, closed without merging