basic qualification section structure, html
front-end-by-rimantas/35-grupe-portfolio-personal pull request #117
Opened 2022-04-24 07:37 UTC by Dovile-dote

2022-04-24 12:56 UTC, krikri89 submitted a review, later dismissed

2022-04-24 14:12 UTC, Paskanas commented on css/pages/about.css
> +@media (min-width: 700px) {
Labai keista kad kitokiu plociu reikia pasikeitimo, matau kad dizaine taip pat tai galim ir taip palikti. Nors atrodo noretųsi standartą turėti, bet ok čia :)

2022-04-24 14:22 UTC, Paskanas requested changes
Palikau smulkių komentarų, bet gražus darbas, norėjau aš šitą išmokti padaryti, tai jau mokėsiu po tavo pvz :)

2022-04-24 14:22 UTC, Paskanas commented on pages/about/index.html
> +        <div class="qualifications-row col-md-6">
Čia ir toliau neveikia klase col-md-6. Kad ji veiktu reikia kad tevas butu row, o tokiu atveju išsikraiko tavo sprendimas. Tai arba reiktu naikinti klase arba siek tiek perdaryti.

2022-04-24 14:22 UTC, Paskanas commented on css/pages/about.css
> +    max-width: 500px;
dėl šitos vietos kai min ekranas tada ne per visa eilute buna. Įdomu kodėl nustatinėjai max-width min ekranui, ar cia del sm ekrano ?

2022-04-24 14:41 UTC, Kristle22 commented
Gerai padirbejai:) is mano puses irgi vienas pastebejimas, kad mazame ekrane 700px visi column elementai yra iscentruoti, o pas tave kaireje puseje, tas max-width sioje vietoje trukdo issicentruoti.

2022-04-24 17:28 UTC, Dovile-dote commented on pages/about/index.html
> +        <div class="qualifications-row col-md-6">
istrinsiu klase, praziopsojau.

2022-04-24 17:32 UTC, Dovile-dote commented on css/pages/about.css
> +    max-width: 500px;
cia su css galima bus koreguot, as ir brake point uzdejau dabar ant 700px, reikia pakeist, bet cia uzduoti kitiems pakursiu :) as kai dariausi struktura, tai buvau visur ir baground uzsidejus ir fiksuotus dydzius, kad matyciau ka darau, gal kazko nesuziurejau ir neistryniau, galesiu pataisyt arba liks tam kas stiliu des.

2022-04-24 17:46 UTC, Paskanas commented on css/pages/about.css
> +    max-width: 500px;
👍

2022-04-25 06:48 UTC, Paskanas approved these changes

2022-04-25 07:39 UTC, krikri89 approved these changes

2022-04-25 07:39 UTC, merged