description&tools exp flex
front-end-by-rimantas/35-grupe-portfolio-personal pull request #121
Opened 2022-04-24 18:11 UTC by Kristle22

2022-04-25 17:30 UTC, krikri89 approved these changes, later dismissed

2022-04-25 20:58 UTC, Dovile-dote requested changes
Man atrodo cia sitoj sekcijoj turi but kazkas va tokio,  gal paciai kils kokiu minciu
<img width="1440" alt="Screen Shot 2022-04-25 at 11 55 07 PM" src="https://user-images.githubusercontent.com/80914644/165173436-03d168c3-d5b6-4e19-b0a0-2358fcc0418b.png">

2022-04-25 20:58 UTC, Dovile-dote requested changes
Man atrodo cia sitoj sekcijoj turi but kazkas va tokio, tik nezinau kas tiksliai ir kaip ieskot, galva nebedirba, gal paciai kils kokiu minciu
<img width="1440" alt="Screen Shot 2022-04-25 at 11 55 07 PM" src="https://user-images.githubusercontent.com/80914644/165173436-03d168c3-d5b6-4e19-b0a0-2358fcc0418b.png">

2022-04-25 22:09 UTC, Kristle22 commented
nu super cssas, ko tik jis neturi:)) idejau progress taga, nereikia dvieju divu:) tik man liko neissprendziamas klausimas, arkazkaip imanoma priversti fleksa destyti elementus stulpeliu, o ne eilute, kad ant didesnio ekrano atsiradus dviem stulpeliams toolsu eiles tvarka nepakistu?

2022-04-25 22:33 UTC, Kristle22 commented
Kadangi kito budo neradau eiles tvarkai palaikyti stulpeliuose, tai sudejau flex order, nors gal tai ir ne esme, bet norejau rasti kazkoki imanoma sprendima.

2022-04-26 06:39 UTC, Dovile-dote approved these changes

2022-04-26 06:53 UTC, Paskanas approved these changes
All good

2022-04-26 06:53 UTC, merged