footer style
front-end-by-rimantas/35-grupe-portfolio-personal pull request #123
Opened 2022-04-24 23:18 UTC by Kristle22

2022-04-25 17:32 UTC, Paskanas requested changes
Fainas darbas, tik gal pading-bottom pamazint noretųsi ir del to i tago palikau komentada. 
Visa kita nice :)

2022-04-25 17:32 UTC, Paskanas commented on index.html
> +          <a href="#"><i class="fa-brands fa-behance"></i></a>
čia pasigavo blog.css kodą i tagui. del to jei pele perbrauki per ikonas vis peles cursor keiciasi. jei butu panaudotas padding butu gražiau. Klausimas ar norejai kad cia taikytusi blog.css kodas? jei taip tai gal reiktu pagalvoti iskelti i base.css failą, nes naudojamas ne vienoje vietoje.

2022-04-25 20:13 UTC, Dovile-dote reviewed
grazu, saunuole!
tik dar sutvarkyk kad kursorius tarp social ikonu nesokinetu, jas reikia suglaust kazkaip, arba uzdet papildoma cursor pointer ant kazkurio elemento. ir dar siulyciau prie ikonu uzdet target="_blank" su linkais i fb, instagram ir t.t svetainiu home page'us. o visa kita super

2022-04-25 21:07 UTC, Kristle22 commented on index.html
> +          <a href="#"><i class="fa-brands fa-behance"></i></a>
pamazinau padding-bottom ir padariau kursoriu ant linku, nes kazkodel buvo tik ant ikonu..

2022-04-25 21:07 UTC, Kristle22 commented
linku home pages iterpti :)

2022-04-26 06:29 UTC, Paskanas reviewed
Dar viena smulkmena- input fielde jei rasai pas mus juoda spalva, o turi buti siek tiek pilka.

2022-04-26 06:33 UTC, Dovile-dote reviewed
juoda ir ten ir pas mus, prisizoomink :) , tik ten raides plonesnes

2022-04-26 07:10 UTC, Paskanas approved these changes

2022-04-26 07:50 UTC, Paskanas requested changes

2022-04-26 07:50 UTC, Paskanas commented on index.html
> +            <button class="submit" type="submit">
uzmesk dar required bus is vis gerai :)

2022-04-26 10:27 UTC, Kristle22 commented on index.html
> +            <button class="submit" type="submit">
ok , uzmesta

2022-04-26 10:56 UTC, Dovile-dote approved these changes

2022-04-26 11:06 UTC, Paskanas approved these changes

2022-04-26 11:06 UTC, merged