Basic structure
front-end-by-rimantas/35-grupe-portfolio-personal pull request #16
Opened 2022-04-12 14:50 UTC by Kristle22

2022-04-12 15:43 UTC, Dovile-dote submitted a review, later dismissed
everything seems good

2022-04-12 18:30 UTC, Paskanas commented on index.html
>      <script src="./js/pages/home.js" defer></script>
Sitas kodas turi buti po html kodo, kitaip jei JS ilgai galvos, vartotojas nieko ekrane nematys. Šitą dalį nukelti į apačia reikėtų

2022-04-12 18:33 UTC, Paskanas requested changes
Reikia išpręsti komentarus.

2022-04-13 06:03 UTC, Paskanas approved these changes
All good :)

2022-04-13 06:03 UTC, Paskanas approved these changes

2022-04-13 06:07 UTC, krikri89 approved these changes
👌

2022-04-13 06:08 UTC, merged