Hero basic structure
front-end-by-rimantas/35-grupe-portfolio-personal pull request #23
Opened 2022-04-13 12:46 UTC by krikri89

2022-04-13 13:05 UTC, Paskanas requested changes
Palikau komentaru

2022-04-13 13:05 UTC, Paskanas commented on index.html
> +        <div class="col-12 col-md-6">
sakyciau pagal dizaina kad kai lg, tai col turetu buti 5 ne 6. Dizaine lieka toks tarpas, o pas mus ne
i kai mazas ekranas, phone, tai turi lygiuotis centre ir ne per visa dydi. gal net col-6, reikia pasibandyti ir palyginti su dizainu

2022-04-13 13:17 UTC, krikri89 commented on index.html
> +        <div class="col-12 col-md-6">
Puikus pastebejimas. Aciu! Pataisiau

2022-04-13 13:19 UTC, krikri89 commented
fixed. thanks

2022-04-13 14:10 UTC, Paskanas approved these changes

2022-04-13 14:13 UTC, Paskanas requested changes
Palikta klaida

2022-04-13 14:13 UTC, Paskanas commented on index.html
> +        <div class="col-lg-6 col-md-6">
manau reiketu palikti kad standariskai col-6, o jei >=lg tai 5 . kitaip sakant <div class="col-12 col-md-6 col-lg-5">
Resolve spaudzia kas paliko komentara. Tau reiktu tik atrasyti kad pataisei.

2022-04-13 14:36 UTC, Dovile-dote commented on index.html
> +          <img src="#" alt="hero-img" class="col-12" />
kodel ant img tago dar uzdeta col-12? jis juk yra div'e, tai manau reiktu det ant pacio divo sia klase. man prie small ekrano nuotraukyte susitraukia i nykstukini dydi, nuo md jau vaziuoja normaliai dydziai

2022-04-13 14:37 UTC, Paskanas commented on index.html
> +        <div class="col-lg-6 col-md-6">
div class="col-12 col-md-6 col-lg-5"

2022-04-13 14:44 UTC, krikri89 commented on index.html
> +        <div class="col-lg-6 col-md-6">
Pakeiciau, nors neatrodo, kad reiktu tokio didellio tarpo.

2022-04-13 14:45 UTC, krikri89 commented on index.html
> +          <img src="#" alt="hero-img" class="col-12" />
tiesa. Pataisiau, aciu

2022-04-13 15:03 UTC, Dovile-dote commented on index.html
> +          <img src="#" alt="hero-img" class="col-12" />
:)

2022-04-13 15:04 UTC, Paskanas commented on index.html
> +        <div class="col-lg-6 col-md-6">
vis dar blogai. kai tampa lg turi likti 6 o ne tapti 12. ne taip turi buti col-lg-12 o col-12

2022-04-13 15:06 UTC, Paskanas requested changes

2022-04-13 15:06 UTC, Paskanas commented on index.html
> +        <div class="col-lg-12 col-md-6 col-lg-5">
prie lg turi likti 6 o ne tapti 12. sitoj vietoj col-lg-12 turejo buti col-12. Yra skirtumas

2022-04-13 15:39 UTC, krikri89 commented on index.html
> +        <div class="col-lg-6 col-md-6">
how about now?

2022-04-13 15:40 UTC, krikri89 commented on index.html
> +        <div class="col-lg-12 col-md-6 col-lg-5">
now?

2022-04-13 16:19 UTC, Dovile-dote commented on index.html
> +        <div class="col-lg-6 col-md-6">
ant sm ekrano tampa nebe col 12, atsiranda tarpai is sonu, manau reiktu dar ikisti col-sm-10 ir ml-sm-1

2022-04-13 16:21 UTC, Dovile-dote commented on index.html
> +        <div class="col-lg-6 col-md-6">
ir foto pereina i col 5 ties xl, prie lg dar 6 laikosi

2022-04-13 18:23 UTC, Paskanas commented on index.html
> +        <div class="col-lg-6 col-md-6">
del tarpu sutikciau, kad pradzioj buna col-10 ml-1, prie sm panasu kad lieka, prie md keiciasi col-6, ir tada col-xl-5

2022-04-13 21:19 UTC, Kristle22 reviewed
Is mano puses tai krito i akis small mode, kad img tagas dizaine neina kartu su tekstu per visa ploti, as pabandyciau kokius col-8 padaryti.

2022-04-14 07:52 UTC, krikri89 commented on index.html
> +        <div class="col-lg-6 col-md-6">
aciu, pataisiau

2022-04-14 12:07 UTC, Paskanas commented on index.html
> +        <div class="col-lg-6 col-md-6">
![image](https://user-images.githubusercontent.com/64682512/163387369-c2a68c63-dc4a-405f-b502-6fa934c6e0a0.png)
sakyciau pradzioj vis tiek turi likti col-10 ne col-12 :)

2022-04-14 12:08 UTC, Paskanas commented on index.html
> +        <div class="col-lg-6 col-md-6">
t.y. col-10 ml-1 col-md-6 ml-md-0 col-xl-5

2022-04-14 12:27 UTC, krikri89 commented on index.html
> +        <div class="col-lg-6 col-md-6">
don't hate me please  :D

2022-04-14 12:27 UTC, Paskanas approved these changes
Super :)

2022-04-14 12:28 UTC, Paskanas commented on index.html
> +        <div class="col-lg-6 col-md-6">
Liuks viskas ;)

2022-04-14 13:37 UTC, Kristle22 approved these changes
Liuks

2022-04-14 13:37 UTC, merged