latest featured projects section structure
front-end-by-rimantas/35-grupe-portfolio-personal pull request #25
Opened 2022-04-13 12:57 UTC by Dovile-dote

2022-04-13 13:28 UTC, Paskanas requested changes
Palikau komentarus

2022-04-13 13:28 UTC, Paskanas commented on index.html
> +        <div class="col-10 ml-1 col-md-8 ml-md-2">
pagal dizaina sakyciau kad cia col-12. tik kad tekstas netelpa tai del to persikelia

2022-04-13 13:28 UTC, Paskanas commented on index.html
> +        <div class="col-8 ml-2 col-md-6 ml-md-3 col-xl-4 ml-xl-4">
kai maziausias ekranas, turi buti per visa ploti, kitaip keliasi i kita eilute, dizaine ne. (sumazinus galima pasitikrinti), veliau didinat ekrana lyg ok

2022-04-13 13:28 UTC, Paskanas commented on index.html
> +        <div class="col-12 col-md-4">
manau cia turi buti col-sm-4, ne col-md-4, lyginant su dizainu. Reikia pataisyti per visus toliau einancius div

2022-04-13 13:38 UTC, Dovile-dote commented on index.html
> +        <div class="col-8 ml-2 col-md-6 ml-md-3 col-xl-4 ml-xl-4">
sutinku, pakeisiu, koja kisa truputi, kad tekstas kol kas necentruotas :)

2022-04-13 13:43 UTC, Dovile-dote commented on index.html
> +        <div class="col-12 col-md-4">
nezinau ar tikrai taip, nes ant dizaino sudeti kiti breake pointai, bet pakeisiu, no problem

2022-04-13 14:16 UTC, Dovile-dote commented on index.html
> +        <div class="col-12 col-md-4">
viska sutvarkiau, patiktinkit ar veikia

2022-04-13 14:17 UTC, Dovile-dote commented on index.html
> +        <div class="col-10 ml-1 col-md-8 ml-md-2">
pakeiciau

2022-04-13 14:24 UTC, Paskanas submitted a review, later dismissed

2022-04-13 20:26 UTC, Kristle22 requested changes
Viskas ok, tik pagal mano aki, as h2 uzdeciau dar papildomai xl mode col-6, vietoj col-8.

2022-04-14 06:49 UTC, Kristle22 approved these changes

2022-04-14 06:56 UTC, krikri89 approved these changes
all good

2022-04-14 06:56 UTC, merged