Headings style
front-end-by-rimantas/35-grupe-portfolio-personal pull request #76
Opened 2022-04-19 19:26 UTC by reginareg

2022-04-20 11:53 UTC, Kristle22 commented
Jei pagal inspekta ziureti, tai section-title yra 36px ir visi kiti atitinkamai mazesni, uzeini i inspecta, paselektini elementa ir ismeta srifta :)

2022-04-20 15:08 UTC, Dovile-dote requested changes
visu pirma, visur sriftas yra popins, ji reiktu parsidownloadinti
pirmoj sekcijoj h1 ant didelio ekrano turi buti 60px, mazdaug prie 991px ekrano dydzio turi pasikeisti i 30px, margin ir is virsaus ir is apacios vienodas, po 20px, nereikia text-align center.  description font-size 14px, padding 0, margin-bottom 16px, kitur 0. ir ta virsuj tekstuka reikia padaryti 14px uppercase ir font-weight suziureti.
kitose visose sekcijose section-title turi buti h2, pereik index.html ir pakeisk kur reikia (my offered services tai tikrai), tada galesi apsirasyti section-title font-size 36px, mazinant ekrana font-size 20px ir kaip nors nurodyti, kad h1.section-title { yra didesnis}. pradziai tiek, istaisyk situos, judesim toliau :)

2022-04-21 12:15 UTC, Dovile-dote approved these changes

2022-04-21 12:31 UTC, Paskanas reviewed
Nepatinka man tas uzspalvojimas tekstu. Siulau bent uzkomentuoti spalvinima jei nenorit keisti. Bet iki tol approve neduosiu

2022-04-21 13:07 UTC, Kristle22 approved these changes

2022-04-21 13:08 UTC, merged

2022-04-21 16:55 UTC, reginareg commented
> Nepatinka man tas uzspalvojimas tekstu. Siulau bent uzkomentuoti spalvinima jei nenorit keisti. Bet iki tol approve neduosiu

Ką turi omeny apie užspalvojimą?