done My Offered Services JS #78
front-end-by-rimantas/35-grupe-portfolio-personal pull request #85
Opened 2022-04-20 13:25 UTC by Paskanas

2022-04-20 14:46 UTC, Dovile-dote submitted a review, later dismissed
good

2022-04-21 10:54 UTC, krikri89 submitted a review, later dismissed

2022-04-21 13:30 UTC, Dovile-dote approved these changes

2022-04-21 13:31 UTC, Dovile-dote requested changes
kazkokie konfliktai lenda, reikia paziuret

2022-04-21 16:56 UTC, Paskanas commented
I6sprendziau konflikta, galite ziureti

2022-04-21 17:36 UTC, Kristle22 approved these changes

2022-04-21 17:39 UTC, krikri89 approved these changes

2022-04-21 19:10 UTC, Dovile-dote approved these changes

2022-04-21 19:10 UTC, merged