plan section hover efect
front-end-by-rimantas/35-grupe-portfolio-personal pull request #94
Opened 2022-04-20 17:14 UTC by Dovile-dote

2022-04-22 11:44 UTC, Paskanas commented
Čia kažkas negerai liko:
![image](https://user-images.githubusercontent.com/64682512/164708193-3df9a965-8c5e-46da-a63f-14e36a4b2c0a.png)

2022-04-22 11:51 UTC, Paskanas requested changes
Užvedus pelę ant planų stumdosi "Latest Posts From Our Blog", būtų gerai kad nesistumdytų. Gal koki aukšti duoti ar pan kad nedidintų sekcijos kai hover'is įvyksta ?

2022-04-22 11:51 UTC, Paskanas commented on css/components/plan.css
> +  /* z-index: 2; */
Čia komentaras ateičiai ar šiaip liko?

2022-04-22 13:01 UTC, Dovile-dote commented on css/components/plan.css
> +  /* z-index: 2; */
del pirmo komentaro, tai prie sitos sekcijos nelindau, pagal inspekta matau, kad ten uzdeta section-description klase. pas mane buvo irgi tokia klase, bet as ja persivadinau i .plan. Pries tai matyt 'mano' klase permusinejo headings stilius, tai cia reikia i headings css listi. galima nauja isues issikelti. arba sutvarkyt sita vieta su konkreciai sios vietos css.
del kitu pastabu pagalvosiu, gal pabandysiu flexa idet, bet maciau tu jau dejai kaip supratau ant visu, tad gal palauksiu kol tavo branchas praeis ir tada patvarkysiu sita vieta.

2022-04-22 13:02 UTC, Dovile-dote commented on css/components/plan.css
> +  /* z-index: 2; */
komentaras paliktas, nes dar ne iki galo sugalvojau kaip ta sokinejima issprest :( tai taip, pusiau ateiciai...

2022-04-22 13:39 UTC, Dovile-dote commented on css/components/plan.css
> +  /* z-index: 2; */
done

2022-04-23 09:08 UTC, Paskanas approved these changes

2022-04-23 13:46 UTC, krikri89 approved these changes

2022-04-23 13:46 UTC, merged